config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :new, :create] do
    # resources of Restaurants using only index, new & create
    resources :reviews, only: [:new, :create]
    # nested resource of reviews inside of restaurants
    # like 1:N - A restaurant have many reviews, but a review belongs to 1 restaurant
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ['chinese', 'italian', 'japanese', 'french', 'belgian'] }
end

# 'presence' and 'true' = must include :key
# 'inclusion { in: ["new array"] }' = Must include elements inside the NEW Array

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

# 'inclusion { in: range inside an array }' = Must include elements inside the existing array

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit]
  # a filter to call the method 'set_restaurant' method in 'Private'
  def index
    @restaurants = Restaurant.all
  end

  def show
    # empty to avoid breaking DRY principle
  end

  def new
    @restaurant = Restaurant.new
    # GET verb
    # creates new restaurant without saving it in a form for the user input
  end

  def edit
    # empty to avoid breaking DRY principle
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    # POST verb
    # creates a new restaurant without saving & passes the params - HASH
    # through restaurant_params
    if @restaurant.save
      # saves restaurant created
      redirect_to restaurants_path
      # redirects created restaurant to home page
      #
    else
      render :new
      # else inherits the code/user input inside of 'new'html.erb
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
    # creates placeholder of ids for restaurant
    # set inside private, but can be accessed with before_action on show & edit
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
    # Keys-values inside of restaurant for 'create' method
  end

  def update
    # PATCH verb
  end

  def destroy
    # DELETE verb
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="form-group">
  <%= form_for(restaurant) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :address %>
    <%= f.text_field :address %>

    <%= f.label :category %>
    <%= f.text_field :category %>
</div>

  <%= f.submit "Add a restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/index.html.erb
<!-- Displays All Restaurants -->

<h1>Restaurants</h1>

<ul class="list-inline card">
  <% @restaurants.each do |restaurant| %>
  <li><%= link_to restaurant.name, restaurants_path(restaurant) %></li>
  <li>Address: <%= restaurant.address%></li>
  <li>Phone number: <%= restaurant.phone_number%></li>
  <li>Category: <%= restaurant.category%></li>
  <% end %>
</ul>

<div>
  <%= link_to "Add a new restaurant", new_restaurant_path, class: "btn btn-primary" %>
</div>

app/views/restaurants/new.html.erb
<!-- A Form to add new Restaurants -->

<%= render 'form', restaurant: @restaurant %>